
:backgroundrb: 
  :port: 11006
  :ip: 0.0.0.0

#:schedules:
#  :test_time_checker_worker:
#    :check_tests_to_finish:
#      :trigger_args:
#        :start: <%= Time.now %>
#        :end: <%= Time.now + 10.minutes %>
#        :repeat_interval: <%= 1.second %>
